name: codequest
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
    # UI Packages
  nes_ui: ^0.24.0
  pixelarticons: ^0.4.0
  google_fonts: ^6.3.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  intl: ^0.20.2
  # Dependencias para el playground de c√≥digo
  flutter_code_editor: ^0.3.0
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  # Audio
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0

dependency_overrides:
  google_fonts: 6.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/characters/
    - assets/images/enemies/
    - assets/images/logo/
    - assets/backgrounds/
    - assets/music/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/logo_app.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo/logo_app.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/logo/logo_app.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo/logo_app.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo/logo_app.png"